[alternate-toggler-nvim]
src.git = "https://github.com/rmagatti/alternate-toggler"
fetch.github = "rmagatti/alternate-toggler"

[lsp-lens-nvim]
src.git = "https://github.com/VidocqH/lsp-lens.nvim"
fetch.github = "VidocqH/lsp-lens.nvim"

[statusline-lua]
src.git = "https://github.com/pupbrained/statusline.lua"
fetch.github = "pupbrained/statusline.lua"

[satellite-nvim]
src.git = "https://github.com/lewis6991/satellite.nvim"
fetch.github = "lewis6991/satellite.nvim"

[buffer-manager-nvim]
src.git = "https://github.com/j-morano/buffer_manager.nvim"
fetch.github = "j-morano/buffer_manager.nvim"

[conceal-nvim]
src.git = "https://github.com/Jxstxs/conceal.nvim"
fetch.github = "Jxstxs/conceal.nvim"

#[diagflow-nvim]
#src.git = "https://github.com/dgagn/diagflow.nvim"
#fetch.github = "dgagn/diagflow.nvim"

[hlchunk-nvim]
src.git="https://github.com/shellRaining/hlchunk.nvim"
fetch.github="shellRaining/hlchunk.nvim"

[hoverhints-nvim]
src.git="https://github.com/soulis-1256/hoverhints.nvim"
fetch.github="soulis-1256/hoverhints.nvim"

[ultimate-autopair-nvim]
src.git="https://github.com/altermo/ultimate-autopair.nvim"
fetch.github="altermo/ultimate-autopair.nvim"
