[alternate-toggler-nvim]
src.git = "https://github.com/rmagatti/alternate-toggler"
fetch.github = "rmagatti/alternate-toggler"

[buffer-manager-nvim]
src.git = "https://github.com/j-morano/buffer_manager.nvim"
fetch.github = "j-morano/buffer_manager.nvim"

[comment-box-nvim]
src.git = "https://github.com/LudoPinelli/comment-box.nvim"
fetch.github = "LudoPinelli/comment-box.nvim"

[conceal-nvim]
src.git = "https://github.com/Jxstxs/conceal.nvim"
fetch.github = "Jxstxs/conceal.nvim"

[glow-hover]
src.git = "https://github.com/Arian8j2/glow-hover.nvim"
fetch.github = "Arian8j2/glow-hover.nvim"

[hlchunk-nvim]
src.git = "https://github.com/shellRaining/hlchunk.nvim"
fetch.github = "shellRaining/hlchunk.nvim"

[hover-nvim]
src.git = "https://github.com/lewis6991/hover.nvim"
fetch.github = "lewis6991/hover.nvim"

[lsp-lens-nvim]
src.git = "https://github.com/VidocqH/lsp-lens.nvim"
fetch.github = "VidocqH/lsp-lens.nvim"

[modes-nvim]
src.git = "https://github.com/mvllow/modes.nvim"
fetch.github = "mvllow/modes.nvim"

[rustaceanvim]
src.git = "https://github.com/mrcjkb/rustaceanvim"
fetch.github = "mrcjkb/rustaceanvim"

[savior-nvim]
src.git = "https://github.com/willothy/savior.nvim"
fetch.github = "willothy/savior.nvim"

[ultimate-autopair-nvim]
src.git = "https://github.com/altermo/ultimate-autopair.nvim"
fetch.github = "altermo/ultimate-autopair.nvim"

[veil-nvim]
src.git = "https://github.com/willothy/veil.nvim"
fetch.github = "willothy/veil.nvim"

[vgit-nvim]
src.git = "https://github.com/tanvirtin/vgit.nvim"
fetch.github = "tanvirtin/vgit.nvim"

[wezterm-nvim]
src.git = "https://github.com/willothy/wezterm.nvim"
fetch.github = "willothy/wezterm.nvim"

[wtf-nvim]
src.git = "https://github.com/pupbrained/wtf.nvim"
fetch.github = "pupbrained/wtf.nvim"
