# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  alternate-toggler-nvim = {
    pname = "alternate-toggler-nvim";
    version = "fe798aa9e4af26c9e33ca1add9d255209d03b108";
    src = fetchFromGitHub {
      owner = "rmagatti";
      repo = "alternate-toggler";
      rev = "fe798aa9e4af26c9e33ca1add9d255209d03b108";
      fetchSubmodules = false;
      sha256 = "sha256-7t0UJ5pIa4BAECf09EodyrXqii9nYsq2n7NDKCoXw78=";
    };
    date = "2023-08-17";
  };
  buffer-manager-nvim = {
    pname = "buffer-manager-nvim";
    version = "4fa47504a23d9a94216f02b1d84f7b0a2dbe2b72";
    src = fetchFromGitHub {
      owner = "j-morano";
      repo = "buffer_manager.nvim";
      rev = "4fa47504a23d9a94216f02b1d84f7b0a2dbe2b72";
      fetchSubmodules = false;
      sha256 = "sha256-a0REAPs0rJIWLvRNZ04ULwjNzH64hYGhrV/+i/9w/TA=";
    };
    date = "2023-11-02";
  };
  conceal-nvim = {
    pname = "conceal-nvim";
    version = "1aff9fc5d1157aef1c7c88b6df6d6db21268d00a";
    src = fetchFromGitHub {
      owner = "Jxstxs";
      repo = "conceal.nvim";
      rev = "1aff9fc5d1157aef1c7c88b6df6d6db21268d00a";
      fetchSubmodules = false;
      sha256 = "sha256-4Nhcjk89WD0Kw9iD0YsZ202tRTWlhFHxhVp2kyoju/Y=";
    };
    date = "2023-12-05";
  };
  hlchunk-nvim = {
    pname = "hlchunk-nvim";
    version = "882d1bc86d459fa8884398223c841fd09ea61b6b";
    src = fetchFromGitHub {
      owner = "shellRaining";
      repo = "hlchunk.nvim";
      rev = "882d1bc86d459fa8884398223c841fd09ea61b6b";
      fetchSubmodules = false;
      sha256 = "sha256-fvFvV7KAOo7xtOCjhGS5bDUzwd10DndAKs3++dunED8=";
    };
    date = "2023-12-11";
  };
  hoverhints-nvim = {
    pname = "hoverhints-nvim";
    version = "86fad985b91fe454469108924c1cdb378cbae1ce";
    src = fetchFromGitHub {
      owner = "soulis-1256";
      repo = "hoverhints.nvim";
      rev = "86fad985b91fe454469108924c1cdb378cbae1ce";
      fetchSubmodules = false;
      sha256 = "sha256-QQ+ISmwY6NnvzsnY2GZVxXh/2V6LYaXIjD7evScq4HQ=";
    };
    date = "2023-11-23";
  };
  lsp-lens-nvim = {
    pname = "lsp-lens-nvim";
    version = "48bb1a7e271424c15f3d588d54adc9b7c319d977";
    src = fetchFromGitHub {
      owner = "VidocqH";
      repo = "lsp-lens.nvim";
      rev = "48bb1a7e271424c15f3d588d54adc9b7c319d977";
      fetchSubmodules = false;
      sha256 = "sha256-zj/Gn/40jnDNh05OFc23LNNuFn1PnIAUDfPquEWpAlk=";
    };
    date = "2023-12-07";
  };
  satellite-nvim = {
    pname = "satellite-nvim";
    version = "7911fa8137c77258ba509ba875ea52c6d59737e8";
    src = fetchFromGitHub {
      owner = "lewis6991";
      repo = "satellite.nvim";
      rev = "7911fa8137c77258ba509ba875ea52c6d59737e8";
      fetchSubmodules = false;
      sha256 = "sha256-k+S1yGHewdXKj/LkiDddkAiEGcGRSyY54HFcNCqhgr8=";
    };
    date = "2023-10-06";
  };
  statusline-lua = {
    pname = "statusline-lua";
    version = "398881da0a6dad3a5fe0f0d3fbafe1280cb1ec43";
    src = fetchFromGitHub {
      owner = "pupbrained";
      repo = "statusline.lua";
      rev = "398881da0a6dad3a5fe0f0d3fbafe1280cb1ec43";
      fetchSubmodules = false;
      sha256 = "sha256-F6VurC1Ukd3CwSdnTZX/9zjIL2VqojnqCnEDAJWn+os=";
    };
    date = "2023-10-31";
  };
  ultimate-autopair-nvim = {
    pname = "ultimate-autopair-nvim";
    version = "b9f40cfba7909a5dbff21fb041b878b102465db9";
    src = fetchFromGitHub {
      owner = "altermo";
      repo = "ultimate-autopair.nvim";
      rev = "b9f40cfba7909a5dbff21fb041b878b102465db9";
      fetchSubmodules = false;
      sha256 = "sha256-BTBcct3g90rdyuE2UeLtPQyAf4J2qxvd0TyQBTOimwE=";
    };
    date = "2023-12-15";
  };
}
