# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  alternate-toggler-nvim = {
    pname = "alternate-toggler-nvim";
    version = "fe798aa9e4af26c9e33ca1add9d255209d03b108";
    src = fetchFromGitHub {
      owner = "rmagatti";
      repo = "alternate-toggler";
      rev = "fe798aa9e4af26c9e33ca1add9d255209d03b108";
      fetchSubmodules = false;
      sha256 = "sha256-7t0UJ5pIa4BAECf09EodyrXqii9nYsq2n7NDKCoXw78=";
    };
    date = "2023-08-17";
  };
  bufferline-nvim = {
    pname = "bufferline-nvim";
    version = "73540cb95f8d95aa1af3ed57713c6720c78af915";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "bufferline.nvim";
      rev = "73540cb95f8d95aa1af3ed57713c6720c78af915";
      fetchSubmodules = false;
      sha256 = "sha256-bHlmaNXfZTlTm/8v48FwCde9ljZFLv25efYF5355bnw=";
    };
    date = "2024-04-22";
  };
  conceal-nvim = {
    pname = "conceal-nvim";
    version = "1aff9fc5d1157aef1c7c88b6df6d6db21268d00a";
    src = fetchFromGitHub {
      owner = "Jxstxs";
      repo = "conceal.nvim";
      rev = "1aff9fc5d1157aef1c7c88b6df6d6db21268d00a";
      fetchSubmodules = false;
      sha256 = "sha256-4Nhcjk89WD0Kw9iD0YsZ202tRTWlhFHxhVp2kyoju/Y=";
    };
    date = "2023-12-05";
  };
  hlchunk-nvim = {
    pname = "hlchunk-nvim";
    version = "882d1bc86d459fa8884398223c841fd09ea61b6b";
    src = fetchFromGitHub {
      owner = "shellRaining";
      repo = "hlchunk.nvim";
      rev = "882d1bc86d459fa8884398223c841fd09ea61b6b";
      fetchSubmodules = false;
      sha256 = "sha256-fvFvV7KAOo7xtOCjhGS5bDUzwd10DndAKs3++dunED8=";
    };
    date = "2023-12-11";
  };
  hover-nvim = {
    pname = "hover-nvim";
    version = "ebdc4c0f967bb36b70bb27763397dd71064c2067";
    src = fetchFromGitHub {
      owner = "lewis6991";
      repo = "hover.nvim";
      rev = "ebdc4c0f967bb36b70bb27763397dd71064c2067";
      fetchSubmodules = false;
      sha256 = "sha256-5yqELR7AUDdPQSnUZpODN0K+SODAmFm3KtFZMW2d8yE=";
    };
    date = "2024-04-23";
  };
  lsp-lens-nvim = {
    pname = "lsp-lens-nvim";
    version = "48bb1a7e271424c15f3d588d54adc9b7c319d977";
    src = fetchFromGitHub {
      owner = "VidocqH";
      repo = "lsp-lens.nvim";
      rev = "48bb1a7e271424c15f3d588d54adc9b7c319d977";
      fetchSubmodules = false;
      sha256 = "sha256-zj/Gn/40jnDNh05OFc23LNNuFn1PnIAUDfPquEWpAlk=";
    };
    date = "2023-12-07";
  };
  modes-nvim = {
    pname = "modes-nvim";
    version = "4035a46aaabe43faf1b54740575af9dd5bb03809";
    src = fetchFromGitHub {
      owner = "mvllow";
      repo = "modes.nvim";
      rev = "4035a46aaabe43faf1b54740575af9dd5bb03809";
      fetchSubmodules = false;
      sha256 = "sha256-Kd2hf5obrPvCVLtRcFjLd75byyrB2o3uYCSEMW6IeCc=";
    };
    date = "2023-12-10";
  };
  rustaceanvim = {
    pname = "rustaceanvim";
    version = "f7dbec708ad07a85abf0543e58fa2ec99cea7f95";
    src = fetchFromGitHub {
      owner = "mrcjkb";
      repo = "rustaceanvim";
      rev = "f7dbec708ad07a85abf0543e58fa2ec99cea7f95";
      fetchSubmodules = false;
      sha256 = "sha256-ctECmikTGj7BO+eyQvw7kyx/MtAwMRhmN4W+rJKo1A0=";
    };
    date = "2024-04-22";
  };
  savior-nvim = {
    pname = "savior-nvim";
    version = "658dd8f169a5c0ed05d2c270d36fcaa87b685a3d";
    src = fetchFromGitHub {
      owner = "willothy";
      repo = "savior.nvim";
      rev = "658dd8f169a5c0ed05d2c270d36fcaa87b685a3d";
      fetchSubmodules = false;
      sha256 = "sha256-iVTVEAIgZW0LZl00nzJPjvctECI3QVSk/ju+5YfHiks=";
    };
    date = "2024-04-23";
  };
  surround-ui-nvim = {
    pname = "surround-ui-nvim";
    version = "65c25088e8dbd1e098245de007498b93c694afb0";
    src = fetchFromGitHub {
      owner = "roobert";
      repo = "surround-ui.nvim";
      rev = "65c25088e8dbd1e098245de007498b93c694afb0";
      fetchSubmodules = false;
      sha256 = "sha256-7RrfLC1pEXstizHb1e0xy9WZS+YkcGnnEIQmh2TFZgk=";
    };
    date = "2023-09-09";
  };
  trouble-nvim = {
    pname = "trouble-nvim";
    version = "b4b9a11b3578d510963f6f681fecb4631ae992c3";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "trouble.nvim";
      rev = "b4b9a11b3578d510963f6f681fecb4631ae992c3";
      fetchSubmodules = false;
      sha256 = "sha256-TjQ8UiV1BqmAddhu9iu+X1HbmCS6SQoIOyXbe8gZRqo=";
    };
    date = "2024-04-22";
  };
  ultimate-autopair-nvim = {
    pname = "ultimate-autopair-nvim";
    version = "6ecf7461d44513af89f8257f057fcc99e9297612";
    src = fetchFromGitHub {
      owner = "altermo";
      repo = "ultimate-autopair.nvim";
      rev = "6ecf7461d44513af89f8257f057fcc99e9297612";
      fetchSubmodules = false;
      sha256 = "sha256-ZyScowo3ATvvWUDwtJHF09vdLKC4oTJgvzxS9ZtLsgU=";
    };
    date = "2024-02-22";
  };
  veil-nvim = {
    pname = "veil-nvim";
    version = "88d5fd48e178a9996985e534cdeded0b2a421881";
    src = fetchFromGitHub {
      owner = "willothy";
      repo = "veil.nvim";
      rev = "88d5fd48e178a9996985e534cdeded0b2a421881";
      fetchSubmodules = false;
      sha256 = "sha256-nvYU6CWt9O45yQvDxqcXpwVVK4AsRiG/iu7U4twhEMY=";
    };
    date = "2023-12-25";
  };
  wtf-nvim = {
    pname = "wtf-nvim";
    version = "51c6bc3fa0d60434bae610c969400e656ce2faaa";
    src = fetchFromGitHub {
      owner = "pupbrained";
      repo = "wtf.nvim";
      rev = "51c6bc3fa0d60434bae610c969400e656ce2faaa";
      fetchSubmodules = false;
      sha256 = "sha256-3icb5uhA7tyZgtSGljEPROQ373LRYz9KJHXXmYrjtfI=";
    };
    date = "2024-04-24";
  };
}
